### ISSUE TITLE
'Metrics' object has no attribute 'stats'

### ISSUE THREAD

**Issue by EdwardZhao1991** [vanvalenlab/deepcell-toolbox#121]
Dear all,

Thanks for sharing this great tool.

The following code has been widely used in the [Mesmer evaluation](https://github.com/vanvalenlab/publication-figures/tree/master/2021-Greenwald_Miller_et_al-Mesmer/notebooks/evaluation).

```python
            # sum metrics across individual images
            for key in self.metrics.stats:
                stats_dict[uid][key] = self.metrics.stats[key][category_idx].sum()
```
I try to run above jupyter notebooks and encounter the following error

> 'Metrics' object has no attribute 'stats'

It seems that `Metrics` in the latest toolbox does not have `stats`.

Which attribute should I use to make to evaluation code work?

**Comment by msschwartz21** [comment]
Can you try installing `deepcell-toolbox==0.9.1`? That release was made before the breaking change to that removed `Metrics.stats` and should be compatible with the code that you are trying to run. Let us know if encounter any other problems.

**Comment by EdwardZhao1991** [comment]
Hi @msschwartz21 ,

Thanks for your help.
However, deepcell-toolbox 0.9.1 is incompatible with the current deep-cell.

Could you tell me how to modify the evaluation code in the jupyter notebooks to make it work with the latest deepcell-toolbox?

**Comment by EdwardZhao1991** [comment]
It would be highly appreciated if you can share a evaluation tutorial jupyter notebook with the latest deepcell-toolbox and deepcell.

**Comment by EdwardZhao1991** [comment]
Hi @ngreenwald , @msschwartz21 ,


1. This function returns jaccard as dice. Is this a bug? 

https://github.com/vanvalenlab/deepcell-toolbox/blob/62279d4a8f4b51570932994bd973d61a6e9bd5db/deepcell_toolbox/metrics.py#L817-L819

2. The jaccard in `ObjectMetrics class` is a pixel-based metric, not object-based metric. right?
https://github.com/vanvalenlab/deepcell-toolbox/blob/62279d4a8f4b51570932994bd973d61a6e9bd5db/deepcell_toolbox/metrics.py#L813-L814
How to generate object level jaccard? (input: y_pred (batch, 256,256), y_true (batch, 256, 256))

**Comment by ngreenwald** [comment]
Hey @EdwardZhao1991, 
I'm going to update the example repo to have pinned versions of both deepcell-tf and metrics so that you won't run into this issue of incompatible versions. I just need to track down exactly what version was used for making the figures in the paper and I'll update the requirements.txt file. You should be good to go then

**Comment by ngreenwald** [comment]
Hey @EdwardZhao1991, I've now updated the [repo](https://github.com/vanvalenlab/publication-figures/tree/master/2021-Greenwald_Miller_et_al-Mesmer) to pinned versions of deepcell (0.9.2) and deepcell-toolbox (0.9.1) so that the code will run as expected. 

The code used to generate the F1 score can be found [here](https://github.com/vanvalenlab/publication-figures/blob/d487de885b07b6b290f792ba58e960f58f6ec4ec/2021-Greenwald_Miller_et_al-Mesmer/Figure_2.py#L470). 

The code used to generate Figure S2d (which was initially Figure S2g before some editorial changes) can be found [here](https://github.com/vanvalenlab/publication-figures/blob/d487de885b07b6b290f792ba58e960f58f6ec4ec/2021-Greenwald_Miller_et_al-Mesmer/Figure_2.py#L338). Let me know if you have any other questions

**Comment by EdwardZhao1991** [comment]
Hi @ngreenwald ,

Thanks for you update.
Could you please answer the other questions (with latest deppcell-toolbox)?

**Comment by ngreenwald** [comment]
@msschwartz21 would be the person to ask for those two questions, I wasn't involved in the refactor.

**Comment by msschwartz21** [comment]
> This function returns jaccard as dice. Is this a bug?
Yes, thanks for catching that issue. I'll work on getting that corrected.

**Comment by ngreenwald** [comment]
For the object-based stats, that function is defined in the repository for generating the figures, it's not part of the metrics package. 

See the code [here](https://github.com/vanvalenlab/publication-figures/blob/d487de885b07b6b290f792ba58e960f58f6ec4ec/2021-Greenwald_Miller_et_al-Mesmer/figures.py#L670)

**Comment by EdwardZhao1991** [comment]
Hi @ngreenwald ,

I'm sorry to bother you.
How to obtain the `metric_predictions` in this function?

https://github.com/vanvalenlab/publication-figures/blob/d487de885b07b6b290f792ba58e960f58f6ec4ec/2021-Greenwald_Miller_et_al-Mesmer/figures.py#L670

**Comment by ngreenwald** [comment]
Hey @EdwardZhao1991, all of these functions are used within that same repo. If you need an example of how it's used, you can search for where it's called

https://github.com/vanvalenlab/publication-figures/blob/d487de885b07b6b290f792ba58e960f58f6ec4ec/2021-Greenwald_Miller_et_al-Mesmer/Figure_2.py#L80
