### ISSUE TITLE
Better metrics for segmentation

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-toolbox#26]
I think we need to spend more time thinking about how segmentation performance is judged. Right now, our usual metrics - recall, precision, F1 score - are biased by the dataset difficulty. One can just throw some easy data into the benchmarking data to get a better score. We should have some way of "normalizing" by dataset difficulty. Some thoughts include running metrics for cells in close proximity or normalizing by cell density.

**Comment by willgraf** [comment]
I believe this issue should be closed due to staleness, as the existing Metrics package does account for various object-based metrics, though I will have #106 close this issue as it is a large refactor of the Metrics code.

Let's reopen this issue when we have a clearer idea of which metrics we'd like to include.
