### ISSUE TITLE
add support to chop for uncorrected training data labels

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-toolbox#27]
Would be great if the chopping script could also take in uncorrected labels produced by algorithm and chop those alongside the raw data to produce a caliban-friendly npz file

**Comment by geneva-miller** [comment]
The overlapping chopper is currently geared towards the pre-annotation pipeline, specifically so that small image pieces can be uploaded to the crowd and then stitched back together later. I think as we move towards using Caliban more, it would make sense to have an npz prep pipeline geared towards Caliban. The chopper was one of the first things that got written when I put together the fig8 pipeline and definitely should be revisited with a broader range of input data in mind.

It will probably be a few weeks before I can work on this. Until then, if you could let me know what you're working with (a bunch of multichannel tifs? uncorrected labels in tif format? other formats?) and how you'd like to process them before working in Caliban, then I can keep those things in mind to make the chopper more flexible.

**Comment by ngreenwald** [comment]
Got it!
From our perspective, we're happy to have our data in whatever format is easiest to help speed up the integration of Caliban into the Figure8 annotation pipeline. We can't use Figure8 for MIBI data until Caliban support gets integrated.

We generally have each FOV as its own folder, and within that folder all the TIFs corresponding to the different channels. However, as part of our segmentation pipeline we already have data structures that are 4D numpy arras of [FOV, channel, rows, cols], which we could also pass directly to the chopper so that it doesn't have to figure out our folder logic. We could add the annotation as one of the channels for the cases where there are already predicted labels that need to be corrected. 

Let me know what you think!

**Comment by ngreenwald** [comment]
I just pushed a first pass at this on the multichannel chopper branch. I'm not sure if you guys have thought much about how to incorporate multichannel data across deepcell; I used xarray for this, would be great to get feedback from you guys if this seems like a good option. 

I added an example notebook. I created two entirely new functions rather than modifying the existing chopper. I mostly just copied over the existing 2D_chopper logic, but definitely further room for streamlining in the future.
